name: Testing
on: push
jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Installing requirements
        run: pip install -r requirements.txt

      - name: Running Unit tests
        run: python3 tests/unit_tests/test_composition.py
